# Generated by Django 5.0.7 on 2024-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sales_sale_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='paydate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='paymentType',
            field=models.CharField(default='Cash', max_length=10),
        ),
    ]
