# Generated by Django 5.0.7 on 2024-10-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sales_paid_sales_paydate_sales_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.CharField(default='no-name', max_length=255),
        ),
    ]
